---
title: "099-map"
author: "joe sweeney"
date: "2026-06-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

loading libs
```{r message=FALSE}
library(sf)
library(ggplot2)
library(leaflet)
library(htmlwidgets)
```

loading shapefile data
```{r message=FALSE}
sites <-leafletsites <- st_read("map-data/2022_Collections/2022_Collections.shp")
#transform to WGS84 (lat/lon) for ggplot2
sites_ll <- st_transform(sites, 4326)

states <- st_read("map-data/States_shapefile/States_shapefile.shp")
states_ll <- st_transform(states, 4326)

nevada <- states[states_ll$State_Name == "NEVADA",]
```

Plot sites on whole state
```{r echo=FALSE}
ggplot() +
  geom_sf(data = nevada) + 
  geom_sf(data = sites_ll)
```


```{r echo=FALSE}
map <- leaflet(sites_ll) %>%
  addProviderTiles(providers$Esri.WorldImagery) %>%
  addPolygons(data = nevada,
              fillColor = "transparent",  
              color = "yellow",           
              weight = 3,                
              opacity = 1) %>%    
  addCircleMarkers(
    radius = 5,
    color = "yellow",
    fillColor = "red",
    fillOpacity = 0.8,
    label = ~Site,
    labelOptions = labelOptions(
      noHide = TRUE,
      direction = "auto",
      textOnly = TRUE,
      style = list(
        "color" = "white",
        "font-size" = "11px",
        "font-weight" = "bold",
        "text-shadow" = "1px 1px 2px black")))
map
```
