---
title: "104-alt-pca"
output: html_document
date: "2026-06-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(vcfR)
library(adegenet)
library(ggpubr)
library(grid)
```

Plan is to make a PCA

Organizing meta (should have 301 fish)

```{r}
fish<-read_tsv("bamlists/nwrk.names", col_names = c("GVL_Code"))
mtot<-read_csv("metadata/meta01222025.csv")
meta<-fish %>% left_join(mtot)
meta
```


```{r, eval=TRUE}
vcf<-read.vcfR(file="outputs/101.2/pruned-nwrk.vcf")
genind<-vcfR2genind(vcf)
genind@pop<-as.factor(meta$`Tributary/Collection Location`)

gen<-genind
X <- tab(gen, NA.method="mean")

pca1 <- dudi.pca(X,scannf=FALSE,scale=FALSE,nf=3)

df<-pca1$li
df<-df %>% bind_cols(meta)
eig<-pca1$eig/sum(pca1$eig)*100
```

```{r}
screedf<-as_tibble(eig) %>% mutate(PC = 1:n()) %>% rename(Var=value)

screedf <- screedf %>% relocate(PC) %>% head(n=20)

a<-ggplot(screedf) +
  geom_line(aes(x=PC, y=Var)) +
  ylab("Percent Variance\n") +
  xlab("\nPrincipal Component") +
  theme_bw() +
  theme(panel.grid = element_blank()) +
  theme(axis.title = element_text(size=14, face = "bold")) +
  scale_x_continuous(breaks=seq(1,20,1))

a
```

```{r}
pc12<-ggplot(df) + 
  geom_point(aes(x=Axis1, y=Axis2, fill=`Tributary/Collection Location`),pch=21, alpha=0.75, cex=2) +
  theme_bw() +
  xlab(paste0("PC1 ",round(eig[1],2), "%")) +
  ylab(paste0("PC2 ",round(eig[2],2), "%")) +
  theme(panel.grid = element_blank()) +
  scale_fill_viridis_d(option="H") +
  guides(fill = guide_legend(override.aes = list(pch = 22))) +
  theme(legend.position = "none") 
  
pc13<-ggplot(df) + 
  geom_point(aes(x=Axis1, y=Axis3, fill=`Tributary/Collection Location`),pch=21, alpha=0.75, cex=2) +
  theme_bw() +
  xlab(paste0("PC1 ",round(eig[1],2), "%")) +
  ylab(paste0("PC3 ",round(eig[3],2), "%")) +
  theme(panel.grid = element_blank()) +
  scale_fill_viridis_d(option="H") +
  guides(fill = guide_legend(override.aes = list(pch = 22))) +
  theme(legend.position = "right") 
pc12
pc13
```

```{r}
blank <- grid.rect(gp=gpar(col="white"))
```

```{r}
ggarrange(ggarrange(a + ggtitle("A") + theme(plot.title=element_text(size=20, face="bold")), blank, ncol=1), 
          pc12 + ggtitle("B") + theme(plot.title=element_text(size=20, face="bold")), 
          pc13 + ggtitle("C") + theme(plot.title=element_text(size=20, face="bold")), 
          ncol=3, widths=c(1.4,1.9,2.5))
ggsave("outputs/104/alt-pca.pdf", width=18, height = 6)
```